// src/pages/shopPage/products.tsx

export interface Product {
  id: number;
  name: string;
  description: string;
  price: number;
  image: string;
  rating: number; // Avaliação de 1 a 5
  category: string; // Categoria do produto
}

export const categories: string[] = [
  'Calçados',
  'Roupas',
  'Acessórios',
  'Hidratação',
  'Segurança e Proteção',
];

const defaultImage = 'https://via.placeholder.com/200x150?text=Imagem+Indisponível';

export const products: Product[] = [
  // Calçados
  {
    id: 1,
    name: 'Tênis de Corrida UltraLight',
    description: 'Tênis leve e confortável para corridas longas.',
    price: 299.99,
    image: 'https://via.placeholder.com/200x150?text=Tênis+UltraLight',
    rating: 4.5,
    category: 'Calçados',
  },
  {
    id: 2,
    name: 'Bicicleta de Corrida',
    description: 'Performance e velocidade em cada pedalada.',
    price: 2999.99,
    image: 'https://via.placeholder.com/200x150?text=Bicicleta+Corrida',
    rating: 4.8,
    category: 'Calçados',
  },
  {
    id: 3,
    name: 'Sapatos Trail Running',
    description: 'Sapatos robustos para trilhas e terrenos irregulares.',
    price: 349.99,
    image: 'https://http2.mlstatic.com/D_NQ_NP_2X_938926-MLB80421576525_112024-F.webp',
    rating: 4.6,
    category: 'Calçados',
  },
  {
    id: 4,
    name: 'Sandália Esportiva',
    description: 'Sandália confortável para atividades leves.',
    price: 129.99,
    image: defaultImage,
    rating: 4.2,
    category: 'Calçados',
  },
  {
    id: 5,
    name: 'Chuteira de Futebol Pro',
    description: 'Chuteira profissional para jogos intensos.',
    price: 399.99,
    image: defaultImage,
    rating: 4.7,
    category: 'Calçados',
  },

  // Roupas
  {
    id: 6,
    name: 'Roupas Técnicas de Corrida',
    description: 'Roupas respiráveis para máxima performance.',
    price: 199.99,
    image: 'https://via.placeholder.com/200x150?text=Roupas+Técnicas',
    rating: 4.3,
    category: 'Roupas',
  },
  {
    id: 7,
    name: 'Shorts com Bolsos Especiais',
    description: 'Conforto e praticidade para suas corridas.',
    price: 119.99,
    image: 'https://via.placeholder.com/200x150?text=Shorts+Especiais',
    rating: 4.2,
    category: 'Roupas',
  },
  {
    id: 8,
    name: 'Vestimenta Térmica',
    description: 'Ideal para corridas em climas frios.',
    price: 159.99,
    image: 'https://via.placeholder.com/200x150?text=Vestimenta+Térmica',
    rating: 4.4,
    category: 'Roupas',
  },
  {
    id: 9,
    name: 'Camisa Dry Fit',
    description: 'Camisa de secagem rápida para máxima ventilação.',
    price: 89.99,
    image: 'https://via.placeholder.com/200x150?text=Camisa+Dry+Fit',
    rating: 4.5,
    category: 'Roupas',
  },
  {
    id: 10,
    name: 'Jaqueta à Prova de Vento',
    description: 'Proteção contra ventos fortes durante as corridas.',
    price: 249.99,
    image: 'https://via.placeholder.com/200x150?text=Jaqueta+Vento',
    rating: 4.6,
    category: 'Roupas',
  },
  {
    id: 11,
    name: 'Calça Legging de Alta Compressão',
    description: 'Leggings que oferecem suporte muscular durante a corrida.',
    price: 149.99,
    image: 'https://via.placeholder.com/200x150?text=Calça+Legging',
    rating: 4.3,
    category: 'Roupas',
  },
  {
    id: 12,
    name: 'Top de Alta Performance',
    description: 'Top confortável e de alta performance para mulheres.',
    price: 129.99,
    image: 'https://via.placeholder.com/200x150?text=Top+Performance',
    rating: 4.4,
    category: 'Roupas',
  },

  // Acessórios
  {
    id: 13,
    name: 'Relógio GPS Esportivo',
    description: 'Monitore suas corridas com precisão e estilo.',
    price: 499.99,
    image: 'https://kidverte.vteximg.com.br/arquivos/ids/176533-1000-1000/Relogio-097002.jpg?v=638139698338030000',
    rating: 4.7,
    category: 'Acessórios',
  },
  {
    id: 14,
    name: 'Meias de Compressão Premium',
    description: 'Melhore sua circulação durante as corridas.',
    price: 59.99,
    image: 'https://via.placeholder.com/200x150?text=Meias+Compressão',
    rating: 4.6,
    category: 'Acessórios',
  },
  {
    id: 15,
    name: 'Bonés Esportivos',
    description: 'Proteja-se do sol com estilo.',
    price: 39.99,
    image: 'https://via.placeholder.com/200x150?text=Bonés+Esportivos',
    rating: 4.4,
    category: 'Acessórios',
  },
  {
    id: 16,
    name: 'Luva de Corrida',
    description: 'Mantenha as mãos aquecidas em corridas frias.',
    price: 49.99,
    image: 'https://via.placeholder.com/200x150?text=Luva+Corrida',
    rating: 4.1,
    category: 'Acessórios',
  },
  {
    id: 17,
    name: 'Fones de Ouvido à Prova d\'Água',
    description: 'Mantenha-se motivado com sua música favorita.',
    price: 149.99,
    image: 'https://via.placeholder.com/200x150?text=Fones+Água',
    rating: 4.5,
    category: 'Acessórios',
  },
  {
    id: 18,
    name: 'Capa de Proteção para Smartphone',
    description: 'Proteja seu celular durante as atividades físicas.',
    price: 69.99,
    image: 'https://via.placeholder.com/200x150?text=Capa+Smartphone',
    rating: 4.4,
    category: 'Acessórios',
  },
  {
    id: 19,
    name: 'Pulseira Reflexiva',
    description: 'Aumente sua visibilidade durante corridas noturnas.',
    price: 29.99,
    image: 'https://via.placeholder.com/200x150?text=Pulseira+Reflexiva',
    rating: 4.3,
    category: 'Acessórios',
  },
  {
    id: 20,
    name: 'Luvas Antiderrapantes',
    description: 'Melhore sua aderência e conforto nas corridas.',
    price: 69.99,
    image: 'https://via.placeholder.com/200x150?text=Luvas+Antiderrapantes',
    rating: 4.3,
    category: 'Acessórios',
  },
  {
    id: 21,
    name: 'Óculos de Proteção UV',
    description: 'Proteja seus olhos durante as corridas ao ar livre.',
    price: 89.99,
    image: 'https://via.placeholder.com/200x150?text=Óculos+UV',
    rating: 4.5,
    category: 'Acessórios',
  },
  {
    id: 22,
    name: 'Cinto de Corrida Ajustável',
    description: 'Cinto confortável com bolsos para itens essenciais.',
    price: 99.99,
    image: 'https://via.placeholder.com/200x150?text=Cinto+Corrida',
    rating: 4.2,
    category: 'Acessórios',
  },

  // Hidratação
  {
    id: 23,
    name: 'Cintos de Hidratação',
    description: 'Mantenha-se hidratado em todas as corridas.',
    price: 89.99,
    image: 'https://via.placeholder.com/200x150?text=Cintos+Hidratação',
    rating: 4.2,
    category: 'Hidratação',
  },
  {
    id: 24,
    name: 'Bebedouro Portátil',
    description: 'Facilite a hidratação durante as corridas.',
    price: 79.99,
    image: 'https://via.placeholder.com/200x150?text=Bebedouro+Portátil',
    rating: 4.2,
    category: 'Hidratação',
  },
  {
    id: 25,
    name: 'Garrafa Isotérmica',
    description: 'Mantenha suas bebidas na temperatura ideal.',
    price: 59.99,
    image: 'https://via.placeholder.com/200x150?text=Garrafa+Isotérmica',
    rating: 4.3,
    category: 'Hidratação',
  },
  {
    id: 26,
    name: 'Tubo de Hidratante',
    description: 'Bebida isotônica para reposição de energia.',
    price: 29.99,
    image: 'https://via.placeholder.com/200x150?text=Tubo+Hidratante',
    rating: 4.4,
    category: 'Hidratação',
  },
  {
    id: 27,
    name: 'Bebedouro com Suporte para Smartphone',
    description: 'Combine hidratação com monitoramento do seu smartphone.',
    price: 109.99,
    image: 'https://via.placeholder.com/200x150?text=Bebedouro+Smartphone',
    rating: 4.3,
    category: 'Hidratação',
  },

  // Segurança e Proteção
  {
    id: 28,
    name: 'Kit de Primeiros Socorros para Corrida',
    description: 'Esteja preparado para pequenos imprevistos.',
    price: 99.99,
    image: 'https://via.placeholder.com/200x150?text=Primeiros+Socorros',
    rating: 4.1,
    category: 'Segurança e Proteção',
  },
  {
    id: 29,
    name: 'Capa de Chuva para Corrida',
    description: 'Corridas seguras mesmo em dias chuvosos.',
    price: 129.99,
    image: 'https://via.placeholder.com/200x150?text=Capa+Chuva',
    rating: 4.0,
    category: 'Segurança e Proteção',
  },
  {
    id: 30,
    name: 'Capacete Aerodinâmico',
    description: 'Segurança e redução de resistência ao vento.',
    price: 499.99,
    image: 'https://via.placeholder.com/200x150?text=Capacete+Aero',
    rating: 4.6,
    category: 'Segurança e Proteção',
  },
];
